### ISSUE TITLE
Sentinel 2 data

### ISSUE THREAD

**Issue by geo-py** [balajiceg/NearShoreBathymetryPlugin#3]
Hello Balaji Ramesh. Sorry to contact you this way but I couldn't find your email address. I was wondering if it is possible to use your plug-in with Sentinel 2 data in QGIS3?

**Comment by balajiceg** [comment]
Sorry for the late reply, I was on a journey.
Yes, you can use Sentinel 2 data also.
If you have any further doubts, shoot them here . I will be happy to reply

**Comment by geo-py** [comment]
Thanks!
