### ISSUE TITLE
Can you use this plugin without ground truthing data?

### ISSUE THREAD

**Issue by geo-py** [balajiceg/NearShoreBathymetryPlugin#4]
Is it possible to carry out SDB without ground truthing data?

**Comment by balajiceg** [comment]
Can you expand SDB

**Comment by geo-py** [comment]
Hello. By SDB I mean Satellite Derived Bathymetry. It is possible to calculate water depth without ground truthing data?

**Comment by balajiceg** [comment]
Obviously not.... if you read the discription of the module you can find that you have to provide some ground truth points
